package com.the4man.cnbdw.model;

import java.util.Date;

public class GomeMemberComlaint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_ID
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private Long comlaintId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.MEMBER_NO
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String memberNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_DIFF
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private Integer comlaintDiff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REGION
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private Integer region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.ORDER_NO
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.ORIGIN
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private Short origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SUBJECT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CONTENT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CMLNT_TIME
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private Date cmlntTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_USER
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String replyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_TIME
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_TIME
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_USER
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String checkUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_SHOW
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_MAIL
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String isMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_PHONE
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String isPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.STATE
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SHOP_NO
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String shopNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_CONTENT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String checkContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SHIPPING_GROUP_ID
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String shippingGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SKU_ID
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    private String skuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_ID
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_ID
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Long getComlaintId() {
        return comlaintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_ID
     *
     * @param comlaintId the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_ID
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setComlaintId(Long comlaintId) {
        this.comlaintId = comlaintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.MEMBER_NO
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.MEMBER_NO
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.MEMBER_NO
     *
     * @param memberNo the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.MEMBER_NO
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_DIFF
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_DIFF
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Integer getComlaintDiff() {
        return comlaintDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_DIFF
     *
     * @param comlaintDiff the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.COMLAINT_DIFF
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setComlaintDiff(Integer comlaintDiff) {
        this.comlaintDiff = comlaintDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REGION
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.REGION
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Integer getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REGION
     *
     * @param region the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.REGION
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setRegion(Integer region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.ORDER_NO
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.ORDER_NO
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.ORDER_NO
     *
     * @param orderNo the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.ORDER_NO
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.ORIGIN
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.ORIGIN
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Short getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.ORIGIN
     *
     * @param origin the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.ORIGIN
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setOrigin(Short origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SUBJECT
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.SUBJECT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SUBJECT
     *
     * @param subject the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.SUBJECT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CONTENT
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.CONTENT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CONTENT
     *
     * @param content the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.CONTENT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CMLNT_TIME
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.CMLNT_TIME
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Date getCmlntTime() {
        return cmlntTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CMLNT_TIME
     *
     * @param cmlntTime the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.CMLNT_TIME
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setCmlntTime(Date cmlntTime) {
        this.cmlntTime = cmlntTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY
     *
     * @param reply the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setReply(String reply) {
        this.reply = reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_USER
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_USER
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getReplyUser() {
        return replyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_USER
     *
     * @param replyUser the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_USER
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setReplyUser(String replyUser) {
        this.replyUser = replyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_TIME
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_TIME
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_TIME
     *
     * @param replyTime the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.REPLY_TIME
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_TIME
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_TIME
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_TIME
     *
     * @param checkTime the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_TIME
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_USER
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_USER
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getCheckUser() {
        return checkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_USER
     *
     * @param checkUser the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_USER
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setCheckUser(String checkUser) {
        this.checkUser = checkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_SHOW
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_SHOW
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_SHOW
     *
     * @param isShow the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_SHOW
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_MAIL
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_MAIL
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getIsMail() {
        return isMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_MAIL
     *
     * @param isMail the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_MAIL
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setIsMail(String isMail) {
        this.isMail = isMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_PHONE
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_PHONE
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getIsPhone() {
        return isPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_PHONE
     *
     * @param isPhone the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.IS_PHONE
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setIsPhone(String isPhone) {
        this.isPhone = isPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.STATE
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.STATE
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.STATE
     *
     * @param state the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.STATE
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SHOP_NO
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.SHOP_NO
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getShopNo() {
        return shopNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SHOP_NO
     *
     * @param shopNo the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.SHOP_NO
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setShopNo(String shopNo) {
        this.shopNo = shopNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_CONTENT
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_CONTENT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getCheckContent() {
        return checkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_CONTENT
     *
     * @param checkContent the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.CHECK_CONTENT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setCheckContent(String checkContent) {
        this.checkContent = checkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SHIPPING_GROUP_ID
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.SHIPPING_GROUP_ID
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getShippingGroupId() {
        return shippingGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SHIPPING_GROUP_ID
     *
     * @param shippingGroupId the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.SHIPPING_GROUP_ID
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setShippingGroupId(String shippingGroupId) {
        this.shippingGroupId = shippingGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SKU_ID
     *
     * @return the value of UAT_PROD_6.GOME_MEMBER_COMLAINT.SKU_ID
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UAT_PROD_6.GOME_MEMBER_COMLAINT.SKU_ID
     *
     * @param skuId the value for UAT_PROD_6.GOME_MEMBER_COMLAINT.SKU_ID
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId;
    }
}