package com.the4man.cnbdw.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class GomeMemberComlaintExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public GomeMemberComlaintExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andComlaintIdIsNull() {
            addCriterion("COMLAINT_ID is null");
            return (Criteria) this;
        }

        public Criteria andComlaintIdIsNotNull() {
            addCriterion("COMLAINT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andComlaintIdEqualTo(Long value) {
            addCriterion("COMLAINT_ID =", value, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andComlaintIdNotEqualTo(Long value) {
            addCriterion("COMLAINT_ID <>", value, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andComlaintIdGreaterThan(Long value) {
            addCriterion("COMLAINT_ID >", value, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andComlaintIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COMLAINT_ID >=", value, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andComlaintIdLessThan(Long value) {
            addCriterion("COMLAINT_ID <", value, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andComlaintIdLessThanOrEqualTo(Long value) {
            addCriterion("COMLAINT_ID <=", value, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andComlaintIdIn(List<Long> values) {
            addCriterion("COMLAINT_ID in", values, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andComlaintIdNotIn(List<Long> values) {
            addCriterion("COMLAINT_ID not in", values, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andComlaintIdBetween(Long value1, Long value2) {
            addCriterion("COMLAINT_ID between", value1, value2, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andComlaintIdNotBetween(Long value1, Long value2) {
            addCriterion("COMLAINT_ID not between", value1, value2, "comlaintId");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNull() {
            addCriterion("MEMBER_NO is null");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNotNull() {
            addCriterion("MEMBER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNoEqualTo(String value) {
            addCriterion("MEMBER_NO =", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotEqualTo(String value) {
            addCriterion("MEMBER_NO <>", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThan(String value) {
            addCriterion("MEMBER_NO >", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO >=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThan(String value) {
            addCriterion("MEMBER_NO <", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_NO <=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLike(String value) {
            addCriterion("MEMBER_NO like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotLike(String value) {
            addCriterion("MEMBER_NO not like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIn(List<String> values) {
            addCriterion("MEMBER_NO in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotIn(List<String> values) {
            addCriterion("MEMBER_NO not in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoBetween(String value1, String value2) {
            addCriterion("MEMBER_NO between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotBetween(String value1, String value2) {
            addCriterion("MEMBER_NO not between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffIsNull() {
            addCriterion("COMLAINT_DIFF is null");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffIsNotNull() {
            addCriterion("COMLAINT_DIFF is not null");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffEqualTo(Integer value) {
            addCriterion("COMLAINT_DIFF =", value, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffNotEqualTo(Integer value) {
            addCriterion("COMLAINT_DIFF <>", value, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffGreaterThan(Integer value) {
            addCriterion("COMLAINT_DIFF >", value, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMLAINT_DIFF >=", value, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffLessThan(Integer value) {
            addCriterion("COMLAINT_DIFF <", value, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffLessThanOrEqualTo(Integer value) {
            addCriterion("COMLAINT_DIFF <=", value, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffIn(List<Integer> values) {
            addCriterion("COMLAINT_DIFF in", values, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffNotIn(List<Integer> values) {
            addCriterion("COMLAINT_DIFF not in", values, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffBetween(Integer value1, Integer value2) {
            addCriterion("COMLAINT_DIFF between", value1, value2, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andComlaintDiffNotBetween(Integer value1, Integer value2) {
            addCriterion("COMLAINT_DIFF not between", value1, value2, "comlaintDiff");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("REGION is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("REGION is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(Integer value) {
            addCriterion("REGION =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(Integer value) {
            addCriterion("REGION <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(Integer value) {
            addCriterion("REGION >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(Integer value) {
            addCriterion("REGION >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(Integer value) {
            addCriterion("REGION <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(Integer value) {
            addCriterion("REGION <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<Integer> values) {
            addCriterion("REGION in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<Integer> values) {
            addCriterion("REGION not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(Integer value1, Integer value2) {
            addCriterion("REGION between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(Integer value1, Integer value2) {
            addCriterion("REGION not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOriginIsNull() {
            addCriterion("ORIGIN is null");
            return (Criteria) this;
        }

        public Criteria andOriginIsNotNull() {
            addCriterion("ORIGIN is not null");
            return (Criteria) this;
        }

        public Criteria andOriginEqualTo(Short value) {
            addCriterion("ORIGIN =", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotEqualTo(Short value) {
            addCriterion("ORIGIN <>", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginGreaterThan(Short value) {
            addCriterion("ORIGIN >", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginGreaterThanOrEqualTo(Short value) {
            addCriterion("ORIGIN >=", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLessThan(Short value) {
            addCriterion("ORIGIN <", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLessThanOrEqualTo(Short value) {
            addCriterion("ORIGIN <=", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginIn(List<Short> values) {
            addCriterion("ORIGIN in", values, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotIn(List<Short> values) {
            addCriterion("ORIGIN not in", values, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginBetween(Short value1, Short value2) {
            addCriterion("ORIGIN between", value1, value2, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotBetween(Short value1, Short value2) {
            addCriterion("ORIGIN not between", value1, value2, "origin");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("SUBJECT is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("SUBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("SUBJECT =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("SUBJECT <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("SUBJECT >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("SUBJECT <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("SUBJECT like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("SUBJECT not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("SUBJECT in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("SUBJECT not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("SUBJECT between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("SUBJECT not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("CONTENT =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("CONTENT <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("CONTENT >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("CONTENT <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("CONTENT <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("CONTENT like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("CONTENT not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("CONTENT in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("CONTENT not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("CONTENT between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("CONTENT not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeIsNull() {
            addCriterion("CMLNT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeIsNotNull() {
            addCriterion("CMLNT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeEqualTo(Date value) {
            addCriterionForJDBCDate("CMLNT_TIME =", value, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("CMLNT_TIME <>", value, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("CMLNT_TIME >", value, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CMLNT_TIME >=", value, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeLessThan(Date value) {
            addCriterionForJDBCDate("CMLNT_TIME <", value, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CMLNT_TIME <=", value, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeIn(List<Date> values) {
            addCriterionForJDBCDate("CMLNT_TIME in", values, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("CMLNT_TIME not in", values, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CMLNT_TIME between", value1, value2, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andCmlntTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CMLNT_TIME not between", value1, value2, "cmlntTime");
            return (Criteria) this;
        }

        public Criteria andReplyIsNull() {
            addCriterion("REPLY is null");
            return (Criteria) this;
        }

        public Criteria andReplyIsNotNull() {
            addCriterion("REPLY is not null");
            return (Criteria) this;
        }

        public Criteria andReplyEqualTo(String value) {
            addCriterion("REPLY =", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotEqualTo(String value) {
            addCriterion("REPLY <>", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyGreaterThan(String value) {
            addCriterion("REPLY >", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyGreaterThanOrEqualTo(String value) {
            addCriterion("REPLY >=", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLessThan(String value) {
            addCriterion("REPLY <", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLessThanOrEqualTo(String value) {
            addCriterion("REPLY <=", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLike(String value) {
            addCriterion("REPLY like", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotLike(String value) {
            addCriterion("REPLY not like", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyIn(List<String> values) {
            addCriterion("REPLY in", values, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotIn(List<String> values) {
            addCriterion("REPLY not in", values, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyBetween(String value1, String value2) {
            addCriterion("REPLY between", value1, value2, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotBetween(String value1, String value2) {
            addCriterion("REPLY not between", value1, value2, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyUserIsNull() {
            addCriterion("REPLY_USER is null");
            return (Criteria) this;
        }

        public Criteria andReplyUserIsNotNull() {
            addCriterion("REPLY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andReplyUserEqualTo(String value) {
            addCriterion("REPLY_USER =", value, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserNotEqualTo(String value) {
            addCriterion("REPLY_USER <>", value, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserGreaterThan(String value) {
            addCriterion("REPLY_USER >", value, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserGreaterThanOrEqualTo(String value) {
            addCriterion("REPLY_USER >=", value, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserLessThan(String value) {
            addCriterion("REPLY_USER <", value, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserLessThanOrEqualTo(String value) {
            addCriterion("REPLY_USER <=", value, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserLike(String value) {
            addCriterion("REPLY_USER like", value, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserNotLike(String value) {
            addCriterion("REPLY_USER not like", value, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserIn(List<String> values) {
            addCriterion("REPLY_USER in", values, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserNotIn(List<String> values) {
            addCriterion("REPLY_USER not in", values, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserBetween(String value1, String value2) {
            addCriterion("REPLY_USER between", value1, value2, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyUserNotBetween(String value1, String value2) {
            addCriterion("REPLY_USER not between", value1, value2, "replyUser");
            return (Criteria) this;
        }

        public Criteria andReplyTimeIsNull() {
            addCriterion("REPLY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReplyTimeIsNotNull() {
            addCriterion("REPLY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReplyTimeEqualTo(Date value) {
            addCriterionForJDBCDate("REPLY_TIME =", value, "replyTime");
            return (Criteria) this;
        }

        public Criteria andReplyTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("REPLY_TIME <>", value, "replyTime");
            return (Criteria) this;
        }

        public Criteria andReplyTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("REPLY_TIME >", value, "replyTime");
            return (Criteria) this;
        }

        public Criteria andReplyTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("REPLY_TIME >=", value, "replyTime");
            return (Criteria) this;
        }

        public Criteria andReplyTimeLessThan(Date value) {
            addCriterionForJDBCDate("REPLY_TIME <", value, "replyTime");
            return (Criteria) this;
        }

        public Criteria andReplyTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("REPLY_TIME <=", value, "replyTime");
            return (Criteria) this;
        }

        public Criteria andReplyTimeIn(List<Date> values) {
            addCriterionForJDBCDate("REPLY_TIME in", values, "replyTime");
            return (Criteria) this;
        }

        public Criteria andReplyTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("REPLY_TIME not in", values, "replyTime");
            return (Criteria) this;
        }

        public Criteria andReplyTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("REPLY_TIME between", value1, value2, "replyTime");
            return (Criteria) this;
        }

        public Criteria andReplyTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("REPLY_TIME not between", value1, value2, "replyTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeIsNull() {
            addCriterion("CHECK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCheckTimeIsNotNull() {
            addCriterion("CHECK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTimeEqualTo(Date value) {
            addCriterion("CHECK_TIME =", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotEqualTo(Date value) {
            addCriterion("CHECK_TIME <>", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeGreaterThan(Date value) {
            addCriterion("CHECK_TIME >", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CHECK_TIME >=", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeLessThan(Date value) {
            addCriterion("CHECK_TIME <", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeLessThanOrEqualTo(Date value) {
            addCriterion("CHECK_TIME <=", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeIn(List<Date> values) {
            addCriterion("CHECK_TIME in", values, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotIn(List<Date> values) {
            addCriterion("CHECK_TIME not in", values, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeBetween(Date value1, Date value2) {
            addCriterion("CHECK_TIME between", value1, value2, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotBetween(Date value1, Date value2) {
            addCriterion("CHECK_TIME not between", value1, value2, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckUserIsNull() {
            addCriterion("CHECK_USER is null");
            return (Criteria) this;
        }

        public Criteria andCheckUserIsNotNull() {
            addCriterion("CHECK_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCheckUserEqualTo(String value) {
            addCriterion("CHECK_USER =", value, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserNotEqualTo(String value) {
            addCriterion("CHECK_USER <>", value, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserGreaterThan(String value) {
            addCriterion("CHECK_USER >", value, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_USER >=", value, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserLessThan(String value) {
            addCriterion("CHECK_USER <", value, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserLessThanOrEqualTo(String value) {
            addCriterion("CHECK_USER <=", value, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserLike(String value) {
            addCriterion("CHECK_USER like", value, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserNotLike(String value) {
            addCriterion("CHECK_USER not like", value, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserIn(List<String> values) {
            addCriterion("CHECK_USER in", values, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserNotIn(List<String> values) {
            addCriterion("CHECK_USER not in", values, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserBetween(String value1, String value2) {
            addCriterion("CHECK_USER between", value1, value2, "checkUser");
            return (Criteria) this;
        }

        public Criteria andCheckUserNotBetween(String value1, String value2) {
            addCriterion("CHECK_USER not between", value1, value2, "checkUser");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNull() {
            addCriterion("IS_SHOW is null");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNotNull() {
            addCriterion("IS_SHOW is not null");
            return (Criteria) this;
        }

        public Criteria andIsShowEqualTo(String value) {
            addCriterion("IS_SHOW =", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotEqualTo(String value) {
            addCriterion("IS_SHOW <>", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThan(String value) {
            addCriterion("IS_SHOW >", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThanOrEqualTo(String value) {
            addCriterion("IS_SHOW >=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThan(String value) {
            addCriterion("IS_SHOW <", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThanOrEqualTo(String value) {
            addCriterion("IS_SHOW <=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLike(String value) {
            addCriterion("IS_SHOW like", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotLike(String value) {
            addCriterion("IS_SHOW not like", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowIn(List<String> values) {
            addCriterion("IS_SHOW in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotIn(List<String> values) {
            addCriterion("IS_SHOW not in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowBetween(String value1, String value2) {
            addCriterion("IS_SHOW between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotBetween(String value1, String value2) {
            addCriterion("IS_SHOW not between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsMailIsNull() {
            addCriterion("IS_MAIL is null");
            return (Criteria) this;
        }

        public Criteria andIsMailIsNotNull() {
            addCriterion("IS_MAIL is not null");
            return (Criteria) this;
        }

        public Criteria andIsMailEqualTo(String value) {
            addCriterion("IS_MAIL =", value, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailNotEqualTo(String value) {
            addCriterion("IS_MAIL <>", value, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailGreaterThan(String value) {
            addCriterion("IS_MAIL >", value, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailGreaterThanOrEqualTo(String value) {
            addCriterion("IS_MAIL >=", value, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailLessThan(String value) {
            addCriterion("IS_MAIL <", value, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailLessThanOrEqualTo(String value) {
            addCriterion("IS_MAIL <=", value, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailLike(String value) {
            addCriterion("IS_MAIL like", value, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailNotLike(String value) {
            addCriterion("IS_MAIL not like", value, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailIn(List<String> values) {
            addCriterion("IS_MAIL in", values, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailNotIn(List<String> values) {
            addCriterion("IS_MAIL not in", values, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailBetween(String value1, String value2) {
            addCriterion("IS_MAIL between", value1, value2, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsMailNotBetween(String value1, String value2) {
            addCriterion("IS_MAIL not between", value1, value2, "isMail");
            return (Criteria) this;
        }

        public Criteria andIsPhoneIsNull() {
            addCriterion("IS_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andIsPhoneIsNotNull() {
            addCriterion("IS_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andIsPhoneEqualTo(String value) {
            addCriterion("IS_PHONE =", value, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneNotEqualTo(String value) {
            addCriterion("IS_PHONE <>", value, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneGreaterThan(String value) {
            addCriterion("IS_PHONE >", value, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("IS_PHONE >=", value, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneLessThan(String value) {
            addCriterion("IS_PHONE <", value, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneLessThanOrEqualTo(String value) {
            addCriterion("IS_PHONE <=", value, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneLike(String value) {
            addCriterion("IS_PHONE like", value, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneNotLike(String value) {
            addCriterion("IS_PHONE not like", value, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneIn(List<String> values) {
            addCriterion("IS_PHONE in", values, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneNotIn(List<String> values) {
            addCriterion("IS_PHONE not in", values, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneBetween(String value1, String value2) {
            addCriterion("IS_PHONE between", value1, value2, "isPhone");
            return (Criteria) this;
        }

        public Criteria andIsPhoneNotBetween(String value1, String value2) {
            addCriterion("IS_PHONE not between", value1, value2, "isPhone");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Short value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Short value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Short value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Short value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Short value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Short value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Short> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Short> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Short value1, Short value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Short value1, Short value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andShopNoIsNull() {
            addCriterion("SHOP_NO is null");
            return (Criteria) this;
        }

        public Criteria andShopNoIsNotNull() {
            addCriterion("SHOP_NO is not null");
            return (Criteria) this;
        }

        public Criteria andShopNoEqualTo(String value) {
            addCriterion("SHOP_NO =", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoNotEqualTo(String value) {
            addCriterion("SHOP_NO <>", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoGreaterThan(String value) {
            addCriterion("SHOP_NO >", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoGreaterThanOrEqualTo(String value) {
            addCriterion("SHOP_NO >=", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoLessThan(String value) {
            addCriterion("SHOP_NO <", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoLessThanOrEqualTo(String value) {
            addCriterion("SHOP_NO <=", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoLike(String value) {
            addCriterion("SHOP_NO like", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoNotLike(String value) {
            addCriterion("SHOP_NO not like", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoIn(List<String> values) {
            addCriterion("SHOP_NO in", values, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoNotIn(List<String> values) {
            addCriterion("SHOP_NO not in", values, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoBetween(String value1, String value2) {
            addCriterion("SHOP_NO between", value1, value2, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoNotBetween(String value1, String value2) {
            addCriterion("SHOP_NO not between", value1, value2, "shopNo");
            return (Criteria) this;
        }

        public Criteria andCheckContentIsNull() {
            addCriterion("CHECK_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andCheckContentIsNotNull() {
            addCriterion("CHECK_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andCheckContentEqualTo(String value) {
            addCriterion("CHECK_CONTENT =", value, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentNotEqualTo(String value) {
            addCriterion("CHECK_CONTENT <>", value, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentGreaterThan(String value) {
            addCriterion("CHECK_CONTENT >", value, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_CONTENT >=", value, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentLessThan(String value) {
            addCriterion("CHECK_CONTENT <", value, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentLessThanOrEqualTo(String value) {
            addCriterion("CHECK_CONTENT <=", value, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentLike(String value) {
            addCriterion("CHECK_CONTENT like", value, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentNotLike(String value) {
            addCriterion("CHECK_CONTENT not like", value, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentIn(List<String> values) {
            addCriterion("CHECK_CONTENT in", values, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentNotIn(List<String> values) {
            addCriterion("CHECK_CONTENT not in", values, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentBetween(String value1, String value2) {
            addCriterion("CHECK_CONTENT between", value1, value2, "checkContent");
            return (Criteria) this;
        }

        public Criteria andCheckContentNotBetween(String value1, String value2) {
            addCriterion("CHECK_CONTENT not between", value1, value2, "checkContent");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdIsNull() {
            addCriterion("SHIPPING_GROUP_ID is null");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdIsNotNull() {
            addCriterion("SHIPPING_GROUP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdEqualTo(String value) {
            addCriterion("SHIPPING_GROUP_ID =", value, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdNotEqualTo(String value) {
            addCriterion("SHIPPING_GROUP_ID <>", value, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdGreaterThan(String value) {
            addCriterion("SHIPPING_GROUP_ID >", value, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("SHIPPING_GROUP_ID >=", value, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdLessThan(String value) {
            addCriterion("SHIPPING_GROUP_ID <", value, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdLessThanOrEqualTo(String value) {
            addCriterion("SHIPPING_GROUP_ID <=", value, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdLike(String value) {
            addCriterion("SHIPPING_GROUP_ID like", value, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdNotLike(String value) {
            addCriterion("SHIPPING_GROUP_ID not like", value, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdIn(List<String> values) {
            addCriterion("SHIPPING_GROUP_ID in", values, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdNotIn(List<String> values) {
            addCriterion("SHIPPING_GROUP_ID not in", values, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdBetween(String value1, String value2) {
            addCriterion("SHIPPING_GROUP_ID between", value1, value2, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andShippingGroupIdNotBetween(String value1, String value2) {
            addCriterion("SHIPPING_GROUP_ID not between", value1, value2, "shippingGroupId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("SKU_ID is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("SKU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(String value) {
            addCriterion("SKU_ID =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(String value) {
            addCriterion("SKU_ID <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(String value) {
            addCriterion("SKU_ID >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_ID >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(String value) {
            addCriterion("SKU_ID <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(String value) {
            addCriterion("SKU_ID <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLike(String value) {
            addCriterion("SKU_ID like", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotLike(String value) {
            addCriterion("SKU_ID not like", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<String> values) {
            addCriterion("SKU_ID in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<String> values) {
            addCriterion("SKU_ID not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(String value1, String value2) {
            addCriterion("SKU_ID between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(String value1, String value2) {
            addCriterion("SKU_ID not between", value1, value2, "skuId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 18 14:51:21 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}