package com.the4man.cnbdw.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public MessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMsgIdIsNull() {
            addCriterion("MSG_ID is null");
            return (Criteria) this;
        }

        public Criteria andMsgIdIsNotNull() {
            addCriterion("MSG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMsgIdEqualTo(String value) {
            addCriterion("MSG_ID =", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotEqualTo(String value) {
            addCriterion("MSG_ID <>", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThan(String value) {
            addCriterion("MSG_ID >", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_ID >=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThan(String value) {
            addCriterion("MSG_ID <", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThanOrEqualTo(String value) {
            addCriterion("MSG_ID <=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLike(String value) {
            addCriterion("MSG_ID like", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotLike(String value) {
            addCriterion("MSG_ID not like", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdIn(List<String> values) {
            addCriterion("MSG_ID in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotIn(List<String> values) {
            addCriterion("MSG_ID not in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdBetween(String value1, String value2) {
            addCriterion("MSG_ID between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotBetween(String value1, String value2) {
            addCriterion("MSG_ID not between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserIsNull() {
            addCriterion("MSG_CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserIsNotNull() {
            addCriterion("MSG_CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserEqualTo(String value) {
            addCriterion("MSG_CREATE_USER =", value, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserNotEqualTo(String value) {
            addCriterion("MSG_CREATE_USER <>", value, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserGreaterThan(String value) {
            addCriterion("MSG_CREATE_USER >", value, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_CREATE_USER >=", value, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserLessThan(String value) {
            addCriterion("MSG_CREATE_USER <", value, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserLessThanOrEqualTo(String value) {
            addCriterion("MSG_CREATE_USER <=", value, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserLike(String value) {
            addCriterion("MSG_CREATE_USER like", value, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserNotLike(String value) {
            addCriterion("MSG_CREATE_USER not like", value, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserIn(List<String> values) {
            addCriterion("MSG_CREATE_USER in", values, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserNotIn(List<String> values) {
            addCriterion("MSG_CREATE_USER not in", values, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserBetween(String value1, String value2) {
            addCriterion("MSG_CREATE_USER between", value1, value2, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgCreateUserNotBetween(String value1, String value2) {
            addCriterion("MSG_CREATE_USER not between", value1, value2, "msgCreateUser");
            return (Criteria) this;
        }

        public Criteria andMsgTitleIsNull() {
            addCriterion("MSG_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andMsgTitleIsNotNull() {
            addCriterion("MSG_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andMsgTitleEqualTo(String value) {
            addCriterion("MSG_TITLE =", value, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleNotEqualTo(String value) {
            addCriterion("MSG_TITLE <>", value, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleGreaterThan(String value) {
            addCriterion("MSG_TITLE >", value, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_TITLE >=", value, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleLessThan(String value) {
            addCriterion("MSG_TITLE <", value, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleLessThanOrEqualTo(String value) {
            addCriterion("MSG_TITLE <=", value, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleLike(String value) {
            addCriterion("MSG_TITLE like", value, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleNotLike(String value) {
            addCriterion("MSG_TITLE not like", value, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleIn(List<String> values) {
            addCriterion("MSG_TITLE in", values, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleNotIn(List<String> values) {
            addCriterion("MSG_TITLE not in", values, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleBetween(String value1, String value2) {
            addCriterion("MSG_TITLE between", value1, value2, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgTitleNotBetween(String value1, String value2) {
            addCriterion("MSG_TITLE not between", value1, value2, "msgTitle");
            return (Criteria) this;
        }

        public Criteria andMsgContentIsNull() {
            addCriterion("MSG_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andMsgContentIsNotNull() {
            addCriterion("MSG_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andMsgContentEqualTo(String value) {
            addCriterion("MSG_CONTENT =", value, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentNotEqualTo(String value) {
            addCriterion("MSG_CONTENT <>", value, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentGreaterThan(String value) {
            addCriterion("MSG_CONTENT >", value, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_CONTENT >=", value, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentLessThan(String value) {
            addCriterion("MSG_CONTENT <", value, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentLessThanOrEqualTo(String value) {
            addCriterion("MSG_CONTENT <=", value, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentLike(String value) {
            addCriterion("MSG_CONTENT like", value, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentNotLike(String value) {
            addCriterion("MSG_CONTENT not like", value, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentIn(List<String> values) {
            addCriterion("MSG_CONTENT in", values, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentNotIn(List<String> values) {
            addCriterion("MSG_CONTENT not in", values, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentBetween(String value1, String value2) {
            addCriterion("MSG_CONTENT between", value1, value2, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgContentNotBetween(String value1, String value2) {
            addCriterion("MSG_CONTENT not between", value1, value2, "msgContent");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeIsNull() {
            addCriterion("MSG_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeIsNotNull() {
            addCriterion("MSG_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeEqualTo(Date value) {
            addCriterion("MSG_CREATE_TIME =", value, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeNotEqualTo(Date value) {
            addCriterion("MSG_CREATE_TIME <>", value, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeGreaterThan(Date value) {
            addCriterion("MSG_CREATE_TIME >", value, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MSG_CREATE_TIME >=", value, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeLessThan(Date value) {
            addCriterion("MSG_CREATE_TIME <", value, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("MSG_CREATE_TIME <=", value, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeIn(List<Date> values) {
            addCriterion("MSG_CREATE_TIME in", values, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeNotIn(List<Date> values) {
            addCriterion("MSG_CREATE_TIME not in", values, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeBetween(Date value1, Date value2) {
            addCriterion("MSG_CREATE_TIME between", value1, value2, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("MSG_CREATE_TIME not between", value1, value2, "msgCreateTime");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIsNull() {
            addCriterion("MSG_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIsNotNull() {
            addCriterion("MSG_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMsgTypeEqualTo(String value) {
            addCriterion("MSG_TYPE =", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotEqualTo(String value) {
            addCriterion("MSG_TYPE <>", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeGreaterThan(String value) {
            addCriterion("MSG_TYPE >", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_TYPE >=", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLessThan(String value) {
            addCriterion("MSG_TYPE <", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLessThanOrEqualTo(String value) {
            addCriterion("MSG_TYPE <=", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeLike(String value) {
            addCriterion("MSG_TYPE like", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotLike(String value) {
            addCriterion("MSG_TYPE not like", value, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeIn(List<String> values) {
            addCriterion("MSG_TYPE in", values, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotIn(List<String> values) {
            addCriterion("MSG_TYPE not in", values, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeBetween(String value1, String value2) {
            addCriterion("MSG_TYPE between", value1, value2, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgTypeNotBetween(String value1, String value2) {
            addCriterion("MSG_TYPE not between", value1, value2, "msgType");
            return (Criteria) this;
        }

        public Criteria andMsgLevelIsNull() {
            addCriterion("MSG_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andMsgLevelIsNotNull() {
            addCriterion("MSG_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andMsgLevelEqualTo(String value) {
            addCriterion("MSG_LEVEL =", value, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelNotEqualTo(String value) {
            addCriterion("MSG_LEVEL <>", value, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelGreaterThan(String value) {
            addCriterion("MSG_LEVEL >", value, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_LEVEL >=", value, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelLessThan(String value) {
            addCriterion("MSG_LEVEL <", value, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelLessThanOrEqualTo(String value) {
            addCriterion("MSG_LEVEL <=", value, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelLike(String value) {
            addCriterion("MSG_LEVEL like", value, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelNotLike(String value) {
            addCriterion("MSG_LEVEL not like", value, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelIn(List<String> values) {
            addCriterion("MSG_LEVEL in", values, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelNotIn(List<String> values) {
            addCriterion("MSG_LEVEL not in", values, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelBetween(String value1, String value2) {
            addCriterion("MSG_LEVEL between", value1, value2, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andMsgLevelNotBetween(String value1, String value2) {
            addCriterion("MSG_LEVEL not between", value1, value2, "msgLevel");
            return (Criteria) this;
        }

        public Criteria andValidityIsNull() {
            addCriterion("VALIDITY is null");
            return (Criteria) this;
        }

        public Criteria andValidityIsNotNull() {
            addCriterion("VALIDITY is not null");
            return (Criteria) this;
        }

        public Criteria andValidityEqualTo(Integer value) {
            addCriterion("VALIDITY =", value, "validity");
            return (Criteria) this;
        }

        public Criteria andValidityNotEqualTo(Integer value) {
            addCriterion("VALIDITY <>", value, "validity");
            return (Criteria) this;
        }

        public Criteria andValidityGreaterThan(Integer value) {
            addCriterion("VALIDITY >", value, "validity");
            return (Criteria) this;
        }

        public Criteria andValidityGreaterThanOrEqualTo(Integer value) {
            addCriterion("VALIDITY >=", value, "validity");
            return (Criteria) this;
        }

        public Criteria andValidityLessThan(Integer value) {
            addCriterion("VALIDITY <", value, "validity");
            return (Criteria) this;
        }

        public Criteria andValidityLessThanOrEqualTo(Integer value) {
            addCriterion("VALIDITY <=", value, "validity");
            return (Criteria) this;
        }

        public Criteria andValidityIn(List<Integer> values) {
            addCriterion("VALIDITY in", values, "validity");
            return (Criteria) this;
        }

        public Criteria andValidityNotIn(List<Integer> values) {
            addCriterion("VALIDITY not in", values, "validity");
            return (Criteria) this;
        }

        public Criteria andValidityBetween(Integer value1, Integer value2) {
            addCriterion("VALIDITY between", value1, value2, "validity");
            return (Criteria) this;
        }

        public Criteria andValidityNotBetween(Integer value1, Integer value2) {
            addCriterion("VALIDITY not between", value1, value2, "validity");
            return (Criteria) this;
        }

        public Criteria andSilentIsNull() {
            addCriterion("SILENT is null");
            return (Criteria) this;
        }

        public Criteria andSilentIsNotNull() {
            addCriterion("SILENT is not null");
            return (Criteria) this;
        }

        public Criteria andSilentEqualTo(String value) {
            addCriterion("SILENT =", value, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentNotEqualTo(String value) {
            addCriterion("SILENT <>", value, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentGreaterThan(String value) {
            addCriterion("SILENT >", value, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentGreaterThanOrEqualTo(String value) {
            addCriterion("SILENT >=", value, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentLessThan(String value) {
            addCriterion("SILENT <", value, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentLessThanOrEqualTo(String value) {
            addCriterion("SILENT <=", value, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentLike(String value) {
            addCriterion("SILENT like", value, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentNotLike(String value) {
            addCriterion("SILENT not like", value, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentIn(List<String> values) {
            addCriterion("SILENT in", values, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentNotIn(List<String> values) {
            addCriterion("SILENT not in", values, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentBetween(String value1, String value2) {
            addCriterion("SILENT between", value1, value2, "silent");
            return (Criteria) this;
        }

        public Criteria andSilentNotBetween(String value1, String value2) {
            addCriterion("SILENT not between", value1, value2, "silent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 27 22:12:24 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}