package com.the4man.cnbdw.model;

import java.util.Date;

public class MessageReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_reply.REPLY_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_reply.MSG_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_reply.REPLY_USER
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String replyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_reply.REPLY_MESSAG
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String replyMessag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_reply.REPLY_TIME
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private Date replyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_reply.REPLY_ID
     *
     * @return the value of message_reply.REPLY_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_reply.REPLY_ID
     *
     * @param replyId the value for message_reply.REPLY_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setReplyId(String replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_reply.MSG_ID
     *
     * @return the value of message_reply.MSG_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_reply.MSG_ID
     *
     * @param msgId the value for message_reply.MSG_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_reply.REPLY_USER
     *
     * @return the value of message_reply.REPLY_USER
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getReplyUser() {
        return replyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_reply.REPLY_USER
     *
     * @param replyUser the value for message_reply.REPLY_USER
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setReplyUser(String replyUser) {
        this.replyUser = replyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_reply.REPLY_MESSAG
     *
     * @return the value of message_reply.REPLY_MESSAG
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getReplyMessag() {
        return replyMessag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_reply.REPLY_MESSAG
     *
     * @param replyMessag the value for message_reply.REPLY_MESSAG
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setReplyMessag(String replyMessag) {
        this.replyMessag = replyMessag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_reply.REPLY_TIME
     *
     * @return the value of message_reply.REPLY_TIME
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_reply.REPLY_TIME
     *
     * @param replyTime the value for message_reply.REPLY_TIME
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }
}