package com.the4man.cnbdw.model;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MSG_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MSG_CREATE_USER
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String msgCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MSG_TITLE
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String msgTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MSG_CONTENT
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String msgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MSG_CREATE_TIME
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private Date msgCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MSG_TYPE
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MSG_LEVEL
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String msgLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.VALIDITY
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private Integer validity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.SILENT
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String silent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MSG_ID
     *
     * @return the value of message.MSG_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MSG_ID
     *
     * @param msgId the value for message.MSG_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MSG_CREATE_USER
     *
     * @return the value of message.MSG_CREATE_USER
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getMsgCreateUser() {
        return msgCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MSG_CREATE_USER
     *
     * @param msgCreateUser the value for message.MSG_CREATE_USER
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setMsgCreateUser(String msgCreateUser) {
        this.msgCreateUser = msgCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MSG_TITLE
     *
     * @return the value of message.MSG_TITLE
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MSG_TITLE
     *
     * @param msgTitle the value for message.MSG_TITLE
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MSG_CONTENT
     *
     * @return the value of message.MSG_CONTENT
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MSG_CONTENT
     *
     * @param msgContent the value for message.MSG_CONTENT
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MSG_CREATE_TIME
     *
     * @return the value of message.MSG_CREATE_TIME
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public Date getMsgCreateTime() {
        return msgCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MSG_CREATE_TIME
     *
     * @param msgCreateTime the value for message.MSG_CREATE_TIME
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setMsgCreateTime(Date msgCreateTime) {
        this.msgCreateTime = msgCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MSG_TYPE
     *
     * @return the value of message.MSG_TYPE
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MSG_TYPE
     *
     * @param msgType the value for message.MSG_TYPE
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MSG_LEVEL
     *
     * @return the value of message.MSG_LEVEL
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getMsgLevel() {
        return msgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MSG_LEVEL
     *
     * @param msgLevel the value for message.MSG_LEVEL
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setMsgLevel(String msgLevel) {
        this.msgLevel = msgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.VALIDITY
     *
     * @return the value of message.VALIDITY
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public Integer getValidity() {
        return validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.VALIDITY
     *
     * @param validity the value for message.VALIDITY
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setValidity(Integer validity) {
        this.validity = validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.SILENT
     *
     * @return the value of message.SILENT
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getSilent() {
        return silent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.SILENT
     *
     * @param silent the value for message.SILENT
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setSilent(String silent) {
        this.silent = silent;
    }
}