package com.the4man.cnbdw.model;

public class MessageRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.RECORD_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.MSG_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.REC_USER
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String recUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.IS_READ
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    private String isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.RECORD_ID
     *
     * @return the value of message_record.RECORD_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.RECORD_ID
     *
     * @param recordId the value for message_record.RECORD_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.MSG_ID
     *
     * @return the value of message_record.MSG_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.MSG_ID
     *
     * @param msgId the value for message_record.MSG_ID
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.REC_USER
     *
     * @return the value of message_record.REC_USER
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getRecUser() {
        return recUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.REC_USER
     *
     * @param recUser the value for message_record.REC_USER
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setRecUser(String recUser) {
        this.recUser = recUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.IS_READ
     *
     * @return the value of message_record.IS_READ
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public String getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.IS_READ
     *
     * @param isRead the value for message_record.IS_READ
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    public void setIsRead(String isRead) {
        this.isRead = isRead;
    }
}