package com.the4man.cnbdw.dao;

import com.the4man.cnbdw.model.GomeMemberComlaint;
import com.the4man.cnbdw.model.GomeMemberComlaintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GomeMemberComlaintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    int countByExample(GomeMemberComlaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    int deleteByExample(GomeMemberComlaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    int deleteByPrimaryKey(Long comlaintId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    int insert(GomeMemberComlaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    int insertSelective(GomeMemberComlaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    List<GomeMemberComlaint> selectByExample(GomeMemberComlaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    GomeMemberComlaint selectByPrimaryKey(Long comlaintId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") GomeMemberComlaint record, @Param("example") GomeMemberComlaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    int updateByExample(@Param("record") GomeMemberComlaint record, @Param("example") GomeMemberComlaintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    int updateByPrimaryKeySelective(GomeMemberComlaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UAT_PROD_6.GOME_MEMBER_COMLAINT
     *
     * @mbggenerated Thu Aug 18 14:51:21 CST 2016
     */
    int updateByPrimaryKey(GomeMemberComlaint record);
}