package com.the4man.cnbdw.dao;

import com.the4man.cnbdw.model.MessageReply;
import com.the4man.cnbdw.model.MessageReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int countByExample(MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int deleteByExample(MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int deleteByPrimaryKey(String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int insert(MessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int insertSelective(MessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    List<MessageReply> selectByExample(MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    MessageReply selectByPrimaryKey(String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageReply record, @Param("example") MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int updateByExample(@Param("record") MessageReply record, @Param("example") MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int updateByPrimaryKeySelective(MessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int updateByPrimaryKey(MessageReply record);
}