package com.the4man.cnbdw.dao;

import com.the4man.cnbdw.model.MessageRecord;
import com.the4man.cnbdw.model.MessageRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int countByExample(MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int deleteByExample(MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int insert(MessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int insertSelective(MessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    List<MessageRecord> selectByExample(MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    MessageRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageRecord record, @Param("example") MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int updateByExample(@Param("record") MessageRecord record, @Param("example") MessageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int updateByPrimaryKeySelective(MessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbggenerated Mon Jun 27 22:12:24 CST 2016
     */
    int updateByPrimaryKey(MessageRecord record);
}